title: Electronic Pet
description: This is the website displaying our final project for ESE5190 in 2024 fall!

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Theme Settings
minimal_mistakes_skin: "sunrise"

# Site Author
author:
  name: "Haichao Zhao"
  location: "Upenn"
  email: "haichao@seas.upenn.edu"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true